import { Page, Text, View, Document, StyleSheet, Image } from '@react-pdf/renderer';

const styles = StyleSheet.create({
  page: {
    padding: 30,
    backgroundColor: '#ffffff',
  },
  header: {
    marginBottom: 20,
    textAlign: 'center',
    borderBottom: '1px solid #e2e8f0',
    paddingBottom: 10,
  },
  title: {
    fontSize: 24,
    fontWeight: 'bold',
    color: '#065f46',
    marginBottom: 5,
  },
  subtitle: {
    fontSize: 12,
    color: '#4b5563',
  },
  section: {
    marginBottom: 20,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: 'bold',
    marginBottom: 10,
    color: '#065f46',
    borderBottom: '1px solid #e2e8f0',
    paddingBottom: 5,
  },
  item: {
    marginBottom: 8,
    fontSize: 12,
    lineHeight: 1.5,
  },
  grid: {
    display: 'flex',
    flexDirection: 'row',
    marginBottom: 15,
  },
  col: {
    flex: 1,
  },
  label: {
    fontWeight: 'bold',
    marginRight: 5,
  },
  severity: {
    backgroundColor: '#f59e0b',
    color: 'white',
    padding: '3px 10px',
    borderRadius: 12,
    fontSize: 10,
    fontWeight: 'bold',
    textTransform: 'uppercase',
  },
  image: {
    width: '100%',
    height: 200,
    objectFit: 'cover',
    marginBottom: 15,
    borderRadius: 8,
  },
  footer: {
    position: 'absolute',
    bottom: 30,
    left: 30,
    right: 30,
    textAlign: 'center',
    fontSize: 10,
    color: '#6b7280',
    borderTop: '1px solid #e2e8f0',
    paddingTop: 10,
  },
});

interface ReportPdfProps {
  analysis: {
    disease: string;
    confidence: number;
    severity: string;
    treatment: {
      immediate: string[];
      preventive: string[];
      organic?: string[];
    };
    estimatedLoss?: string;
    localizedText?: string;
  };
  imageUrl?: string;
  location?: {
    latitude: number;
    longitude: number;
  };
  notes?: string;
  language?: string;
}

export const ReportPdf = ({ analysis, imageUrl, location, notes, language }: ReportPdfProps) => (
  <Document>
    <Page size="A4" style={styles.page}>
      <View style={styles.header}>
        <Text style={styles.title}>Crop Health Report</Text>
        <Text style={styles.subtitle}>Generated on {new Date().toLocaleDateString()}</Text>
      </View>

      {imageUrl && (
        <View style={styles.section}>
          {/* eslint-disable-next-line jsx-a11y/alt-text */}
          <Image src={imageUrl} style={styles.image} />
        </View>
      )}

      <View style={styles.section}>
        <View style={styles.grid}>
          <View style={styles.col}>
            <Text style={styles.item}><Text style={styles.label}>Disease:</Text> {analysis.disease}</Text>
            <Text style={styles.item}><Text style={styles.label}>Confidence:</Text> {analysis.confidence}%</Text>
          </View>
          <View style={styles.col}>
            <Text style={styles.item}><Text style={styles.label}>Severity:</Text> 
              <Text style={styles.severity}> {analysis.severity}</Text>
            </Text>
            {location && (
              <Text style={styles.item}>
                <Text style={styles.label}>Location:</Text> {location.latitude.toFixed(4)}, {location.longitude.toFixed(4)}
              </Text>
            )}
          </View>
        </View>
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Immediate Actions (Next 24 Hours)</Text>
        {analysis.treatment.immediate.map((item: string, index: number) => (
          <Text key={index} style={styles.item}>• {item}</Text>
        ))}
      </View>

      <View style={styles.section}>
        <Text style={styles.sectionTitle}>Preventive Measures</Text>
        {analysis.treatment.preventive.map((item: string, index: number) => (
          <Text key={index} style={styles.item}>• {item}</Text>
        ))}
      </View>

      {analysis.treatment.organic && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Organic Alternatives</Text>
          {analysis.treatment.organic.map((item: string, index: number) => (
            <Text key={index} style={styles.item}>• {item}</Text>
          ))}
        </View>
      )}

      {analysis.localizedText && (
         <View style={styles.section}>
            <Text style={styles.sectionTitle}>Translation {language ? `(${language})` : ''}</Text>
            <Text style={styles.item}>{analysis.localizedText}</Text>
         </View>
        )}

      {notes && (
        <View style={styles.section}>
          <Text style={styles.sectionTitle}>Additional Notes</Text>
          <Text style={styles.item}>{notes}</Text>
        </View>
      )}

      <Text style={styles.footer}>
        Generated by SmartFarm Advisor • {new Date().getFullYear()}
      </Text>
    </Page>
  </Document>
);
